OPENAI_API_KEY = "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"  # Replace with your actual key
